<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto

namespace GPBMetadata;

class Example
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa3010a0d6578616d706c652e70726f746f12076578616d706c65221e0a" .
            "0b4563686f52657175657374120f0a076d65737361676518012001280922" .
            "1f0a0c4563686f526573706f6e7365120f0a076d65737361676518012001" .
            "280932400a074578616d706c6512350a044563686f12142e6578616d706c" .
            "652e4563686f526571756573741a152e6578616d706c652e4563686f5265" .
            "73706f6e73652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

